postinstall más bonito.

diff --git a/trunk/aon-gta/src/main/scripts/postinstall b/trunk/aon-gta/src/main/scripts/postinstall
--- a/trunk/aon-gta/src/main/scripts/postinstall
+++ b/trunk/aon-gta/src/main/scripts/postinstall
@@ -60,17 +60,17 @@ function aondir_dbconnection
 
 function dbconnection_host
 {
-	perl -e 'if ( "'$1'" =~ /jdbc:mysql:\/\/(.*):/ ) { print "$1" }'
+	perl -e 'if ( "'$1'" =~ /jdbc:mysql:\/\/(.*)[:|\/]/ ) { print "$1" }'
 }
 
 function dbconnection_port
 {
-	perl -e 'if ( "'$1'" =~ /jdbc:mysql:\/\/.*:(.*)\// ) { print "$1" }'
+	perl -e 'if ( "'$1'" =~ /jdbc:mysql:\/\/.*:(.*)\// ) { print "$1" } else { print "3306" }'
 }
 
 function dbconnection_dbname
 {
-	perl -e 'if ( "'$1'" =~ /jdbc:mysql:\/\/.*:.*\/([^?]*)/ ) { print "$1" }'
+	perl -e 'if ( "'$1'" =~ /jdbc:mysql:\/\/.*\/([^?]*)/ ) { print "$1" }'
 }
 
 
@@ -86,6 +86,7 @@ for DOMAIN in $(aondir_domains); do
 	if aondir_domain_has_app $DOMAIN aon-gta; then 
 		DATASOURCE=`aondir_datasource aon-gta  $DOMAIN`
 		DBCONNECTION=`aondir_dbconnection $DATASOURCE`		
+		echo -n "UPDATING '$DBCONNECTION'..."
 		mysql \
 -u `aondir_dbuser $DATASOURCE` \
 -h `dbconnection_host  $DBCONNECTION` \
@@ -98,5 +99,6 @@ UPDATE income SET status = 1 WHERE status = 2; \
 UPDATE income SET workplace = (SELECT MIN(id) FROM workplace) WHERE workplace is NULL;\
 UPDATE delivery SET workplace = (SELECT MIN(id) FROM workplace) WHERE workplace is NULL;\
 COMMIT;';
+	[[ $? -eq 0 ]] && echo -e "\\033[1;32mOK\\033[0;39m" || echo -e "\\033[1;31mERROR\\033[0;39m";
 	fi  
 done
